<?php

namespace App\Http\Resources;

use Illuminate\Http\Resources\Json\JsonResource;
use Carbon\Carbon;

class ClientResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        // return parent::toArray($request);

        return [
            'brCode' => $this->ClientIDBrCode,
            'clientId' => $this->ClientID,
            'chkDgt' => $this->ClientIDChkDgt,
            'lastName' => $this->LName,
            'firstName' => $this->FName,
            'middleName' => $this->MName,
            'clientTypeId' => $this->ClientTypeID,
            'clientTypeName' => $this->ClientTypeDesc,
            'accountStatusId' => $this->AcctStatID,
            'accountStatusName' => $this->AcctStatDesc,
            'alertLevel' => $this->AlertLevel,
            'referenceId' => $this->OldClientID,
            'oldPsbn' => $this->OldPSBN,
            'suffix' => $this->SName,
            'accountName' => $this->AccountName,
            'collector' => $this->Collector,
            'dateOpened' => Carbon::parse($this->DateOpened)->format('Y-m-d'),
            'acctType' => $this->AccountType,
            'clientType' => $this->ClientType,
            'accountStatus' => $this->AccountStatus,
            'jointType' => $this->JointType,
            'oldClientName' => $this->OldClientName,
            'dateOfBirth' => Carbon::parse($this->DateOfBirth)->format('Y-m-d'),
            'gender' => $this->Gender,
            'civilStatus' => $this->CivilStatus,
            'education' => $this->EducAttained,
            'tin' => $this->TINNum,
            'ctcno' => $this->CTCNumber,
            'sss' => $this->SSSGSISNum,
            'philHealth' => $this->PhilHealthNum,
            'pagIbig' => $this->PagibigNum,
            'atmBank' => $this->ATMBank,
            'atmNo' => $this->ATMNum ,
            'schoolLastAttended' => Carbon::parse($this->SchoolLastAttended)->format('Y-m-d') ,
            'profession' => $this->Profession,
            'sectoral' => $this->Sectoral,
            'occupational' => $this->Occupational,
            'geographical' => $this->Geographical,
            'remarks' => $this->Remarks,
            'homeTelNo' => $this->ResTelNum,
            'provinceTelNo' => $this->ProvTelNum,
            'cellphoneNo' => $this->CellNum,
            'employerTelNo' => $this->EmpBusTelNum,
            'otherContactNo' => $this->OtherContactNum,
            'spouseCellNo' => $this->SpCellNum,
            'emailAddress' => $this->EmailAddress,
            'mailingAddress' => $this->MailingAddress,
            'resAddStreet' => $this->ResAddStreet,
            'resAddBarangay' => $this->ResAddBarangay,
            'resAddCity' => $this->ResAddCity,
            'resAddProvince' => $this->ResAddProvince,
            'resAddZipCode' => $this->ResAddZipCode,
            'resSince' => Carbon::parse($this->ResSince)->format('Y-m-d'),
            'resType' => $this->ResType ,
            'provAddStreet' => $this->ProvAddStreet ,
            'provAddBarangay' => $this->ProvAddBarangay,
            'provAddCity' => $this->ProvAddCity ,
            'provAddProvince' => $this->ProvAddProvince ,
            'provAddZipCode' => $this->ProvAddZipCode,
            'provSince' => Carbon::parse($this->ProvSince)->format('Y-m-d'),
            'provType' => $this->ProvType,
            'busAddStreet' => $this->BusAddStreet,
            'busAddBarangay' => $this->BusAddBarangay,
            'busAddCity' => $this->BusAddCity,
            'busAddProvince' => $this->BusAddProvince,
            'busAddZipCode' => $this->BusAddZipCode,
            'spBusAddStreet' => $this->SpBusAddStreet,
            'spBusAddBarangay' => $this->SpBusAddBarangay,
            'spBusAddCity' => $this->SpBusAddCity,
            'spBusAddProvince' => $this->SpBusAddProvince,
            'spBusAddZipCode' => $this->SpBusAddZipCode,
            'employerName' => $this->BusName,
            'nature' => $this->BusNature,
            'since' => $this->BusSince,
            'numberOfEmployees' => $this->BusNumEmployees,
            'jobTitle' => $this->BusJobTitle ,
            'jobStatus' => $this->BusStatus ,
            'dateHired' => Carbon::parse($this->BusDateHired)->format('Y-m-d'),
            'employmentLevel' => $this->BusLevel,
            'otherIncome' => $this->BusOtherSourceOfIncome,
            'busProfessionCode' => $this->BusProfessionCode,
            'busProfessions' => $this->BusProfession,
            'busOccupationCode' => $this->BusOccupationCode,
            'busOccupation' => $this->BusOccupation,
            'spFName' => $this->SpFName,
            'spMName' => $this->SpMName,
            'spLName' => $this->SpLName,
            'spSuffix' => $this->SpSName,
            'spGender' => $this->SpGender,
            'spDateOfBirth' => Carbon::parse($this->SpDateofBirth)->format('Y-m-d'),
            'spOccupational' => $this->SpOccupational,
            'spBusinessName' => $this->SpBusName,
            'spJobTitle' => $this->SpBusJobTitle,
            'spJobStatus' => $this->SpBusStatus,
            'spSince' => $this->SpBusSince,
            'spHired' => Carbon::parse($this->SpBusDateHired)->format('Y-m-d'),
            'spEmpLevel' => $this->SpBusLevel,
            'spNature' => $this->SpBusNature,
            'spNumberOfEmployees' => $this->SpBusNumEmployees,
            'spOtherIncome' => $this->SpOtherSourceOfIncome,
            'dateClosed' => Carbon::parse($this->ClosedDate)->format('Y-m-d'),
            'reason' => $this->ClosedReason,
            'dateTransferred' => $this->DateTransferred,
            'closedDestBranch' => $this->ClosedDestBranch,
            'originBranch' => $this->OriginBranch,
            'updUser' => $this->UpdUser,
            'updDateTime' => $this->UpdDateTime,
            'driversLicense' => $this->DriverLicenseNum,
            'dateDeceased' => $this->DateDeceased ,
            'encdBy' => $this->EncdBy,
            'encdDateTime' => $this->EncdDateTime,
            'rating' => $this->Rating,
            'employmentId' => $this->BusEmpID,
            'sSpExcluded' => $this->SSPExcluded,
            'dosriTag' => $this->DOSRITag,
            'dosriRelatedTo' => $this->DOSRIRelatedTo,
            'spEducAttained' => $this->SpEducAttained ,
            'spDegree' => $this->SpDegreeCourse,
            'spOccupation' => $this->SpOccupation ,
            'spMonthlyIncome' => $this->SpMonthlyIncome ,
            'height' => $this->Height ,
            'weight' => $this->Weight ,
            'shareCapitalPledge' => $this->SCPledge ,
            'shareDepositPledge' => $this->SDPledge ,
            'isShowTotalPoints' => $this->IsShowTotalPoints ,
            'recruitedBy' => $this->RecruiterID ,
            'gsis' => $this->GSISNum ,
            'nso' => $this->NSONum ,
            'votersId' => $this->VotersID ,
            'pmesBatchNum' => $this->PMESBatchNum,
            'otherId' => $this->OtherIDNum ,
            'pmesDate' => $this->PMESDate ,
            'employerCode' => $this->EmpCode ,
            'monthlySalary' => $this->BusinessIncome ,
            'mealAllowance' => $this->MealAllowance ,
            'department' => $this->ClientDEPT ,
            'smsBroadcastNo' => $this->SMSNumber ,
            'school' => $this->SchoolID ,
            'section' => $this->SectionID ,
            'restriction' => $this->RestrikID ,
            'religion' => $this->Religion ,
            'cisaClientTitle' => $this->CISAclientTitle,
            'cisaMothersFname' => $this->CISAmothersFname,
            'cisaMothersLname' => $this->CISAmothersLname,
            'cisaMothersMname' => $this->CISAmothersMname,
            'cisaFathersFname' => $this->CISAfathersFname,
            'cisaFathersLname' => $this->CISAfathersLname,
            'cisaFathersNameExtnt' => $this->CISAfathersNameExtnt,
            'cisaFathersMname' => $this->CISAfathersMname,
            'cisaPsocCode' => $this->CISAPSOC_CODE,
            'cisaPsicCode' => $this->CISAPSIC_CODE,
            'cisaContactType' => $this->CISA_ContactType,
            'cisaContactNum' => $this->CISA_ContactNum,
            'cisaBirthPlace' => $this->CISA_BirthPlace,
            'isCisaUpdated' => $this->isCISAUpdated,
            'resAddStrNo' => $this->ResAddStrNo ,
            'provAddStrNo' => $this->ProvAddStrNo ,
            'busAddStrNo' => $this->BusAddStrNo ,
            'sPouseStrNo' => $this->SpouseStrNo ,
            'subGroup' => $this->Geo_SubgroupID ,   
        ];
    }
}
