<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/{any}', 'ClientPageController@index');

Route::get('/home', 'HomeController@index');
Route::get('/', 'LoginController@index');
Route::post('/', 'Auth\LoginController@login');
Route::get('/register', 'UserRegisterController@index');

Route::prefix('client')->group(function (){
    Route::get('/', 'ClientPageController@index');
    Route::get('/{id}', 'ClientPageController@index');
    Route::get('search', 'ClientSearchController@index');
    Route::get('{id}/beneficiaries', 'BeneficiariesPageController@index');
    Route::get('{id}/personal-references', 'PersonalReferencesPageController@index');
    Route::get('{id}/credit-bank-references', 'CreditBankReferencesPageController@index');
    Route::get('{id}/joints', 'JointPageController@index');
    Route::get('master-list', 'ClientMasterListController@index');
    Route::get('statement-of-account', 'ClientStatementOfAccountController@index');
    Route::get('{id}/sl-account-summary', 'SlAccountSummaryPageController@index');
    Route::get('transfer-sl-accounts', 'ClientTransferSlAccountsController@index');
    Route::get('{id}/comakertoinquiry', 'CoMakerPageController@index');
    Route::get('{id}/activitylogs', 'ActivityLogsPageController@index');
    Route::get('{id}/generation-verification-code', 'GenerationVerificationCodePageController@index');
});

Route::prefix('front-office')->group(function (){
    Route::get('/', 'FrontOfficePageController@index');
    Route::get('start-of-day', 'StartOfDayPageController@index');
    Route::get('passbook-printing', 'PassbookPrintController@index');
    Route::get('passbook-printing/{id}', 'PassbookPrintController@index');
    Route::get('passbook-printing/{passBkBrCode}/{passBkClientId}/{passBkSlcCode}/{passBkSltCode}/{passBkRefNo}', 'PassbookPrintController@index');
    Route::get('end-of-day', 'EndOfDayController@index');
    Route::get('atm-gateway', 'ATMGatewayController@index');
    Route::get('request-server', 'RequestServerController@index');
    Route::get('ccoi-transaction', 'CCOITransactionController@index');
    Route::get('front-office-report', 'FrontOfficeReportsController@index');
    Route::get('over-ride', 'OverRideController@index');
    Route::get('clearing-ac-utility', 'ClearingAcUtilityController@index');
    Route::get('transaction', 'TransactionController@index');
    Route::get('transaction/{trCode}/{trYear}/{trCtlNo}/{trDocNo}', 'TransactionController@index');
    Route::get('transaction/{id}', 'TransactionController@index');
    Route::get('priority-system-display', 'FOPrioritySystemDisplayPageController@index');
    Route::get('inquiry', 'FOInquiryPageController@index');
    Route::get('inquiry/{trCode}/{trYear}/{trCtlNo}/{trDocNo}', 'FOInquiryPageController@index');
    Route::get('inquiry/{id}', 'FOInquiryPageController@index');
    Route::get('cash-transfers', 'FOCashTransfersPageController@index');
    Route::get('cash-collection', 'FOCashCollectionPageController@index');
    Route::get('bank-deposits', 'FOBankDepositsPageController@index');
    Route::get('cash-disbursements', 'FOCashDisbursementsPageController@index');
    Route::get('transaction-listing', 'FOTransactionListingPageController@index');
    Route::get('passbook-printing-search', 'PassBkSearchController@index');
    Route::get('passbook-printing-search/{id}/passbook-printing-search-passbook', 'PassBkSearchController@index');
    Route::get('transaction-search', 'TransactionSearchController@index');
    Route::get('transaction-search-trans', 'TransactionSearchTransController@index');
    Route::get('inquiry-search', 'InquirySearchController@index');
});

Route::prefix('back-office')->group(function (){
    Route::get('/', 'BackOfficePageController@index');
    Route::get('inquiry', 'BackOfficeInquiryController@index');
    Route::get('fs-consolidation', 'FsConsolidationPageController@index');
    Route::get('generaljournal', 'GeneralJournalPageController@index');
    Route::get('disbursements', 'DisbursementsPageController@index');
    Route::get('upload', 'BOUploadPageController@index');
    Route::get('bpr-maintenance', 'BprMaintenancePageController@index');
    Route::get('general-journal-inquiry', 'GeneralJournalInquiryPageController@index');
    Route::get('disbursements-inquiry', 'DisbursementsInquiryPageController@index');
    Route::get('cash-receipts-inquiry', 'CashReceiptsInquiryPageController@index');
    Route::get('report-generation', 'ReportGenerationPageController@index');
    Route::get('balance-sheet-report', 'BalanceSheetReportPageController@index');
    Route::get('income-statement-report', 'IncomeStatementReportPageController@index');
    Route::get('trial-balance-report', 'TrialBalanceReportPageController@index');
    Route::get('general-ledger-report', 'GeneralLedgerReportPageController@index');
    Route::get('gl-trans-summary-report', 'GlTransSummaryReportPageController@index');
    Route::get('general', 'GeneralPageController@index');
    Route::get('sl-option', 'SlOptionPageController@index');
    Route::get('advanced', 'AdvancedPageController@index');
    Route::get('maintenance', 'MaintenancePageController@index');
    Route::get('inquiry-search', 'BOInquirySearchPageController@index');
    Route::get('generate', 'BOGeneratePageController@index');
    Route::get('override', 'BOOverrideController@index');
    Route::get('general-journal-search', 'BOGeneralJournalSearchPageController@index');
    Route::get('general-journal-inquiry-search', 'BOGeneralJournalInquirySearchPageController@index');
    Route::get('general-journal/{trCode}/{trYear}/{trCtlNo}/{trDocNo}','GeneralJournalPageController@index');
    Route::get('bpr-maintenance-search', 'BOBprMaintenanceSearchPageController@index');
    Route::get('bpr-maintenance/{trCode}/{trYear}/{trCtlNo}/{trDocNo}','BprMaintenancePageController@index');
    Route::get('general-journal-inquiry/{trCode}/{trYear}/{trCtlNo}/{trDocNo}','GeneralJournalInquiryPageController@index');
});

Route::prefix('loans')->group(function (){
    Route::get('/', 'LoansPageController@index');
    Route::get('loans-application-module', 'LoansAppModuleController@index');
    Route::get('loans-application-module/{id}/{brCode}','LoansAppModuleController@index');
    Route::get('loans-application-module/{id}/{brCode}/loans-account-number-inquiry','LoansAppModuleController@index');
    Route::get('loans-application-module/{clientId}/{brCode}/{refNo}/{slcCode}/{sltCode}','LoansAppModuleController@index');
    Route::get('loans-application-module/{laclientId}/{laId}/loan-app','LoansAppModuleController@index');
    Route::get('loans-master', 'LoansMasterController@index');
    Route::get('loans-master/{id}','LoansMasterController@index');
    Route::get('loans-master/{id}/loan-search-loan','LoansMasterController@index');
    Route::get('loans-master/{loanBrCode}/{loanSlcCode}/{loanSltCode}/{loanRefNo}/{clientIdLoan}', 'LoansMasterController@index');
    Route::get('loan-ar-master', 'LoansARMasterController@index');
    Route::get('loan-ar-master/{id}', 'LoansARMasterController@index');
    Route::get('loan-ar-master/{id}/ar-search-loan', 'LoansARMasterController@index');
    Route::get('loan-ar-master/{arBrCode}/{arSlcCode}/{arSltCode}/{arRefNo}/{clientIdAr}', 'LoansARMasterController@index');
    Route::get('loans-master-inquiry', 'LoansMasterInquiryController@index');
    Route::get('loans-master-inquiry/{id}', 'LoansMasterInquiryController@index');
    Route::get('loans-master-inquiry/{arBrCode}/{arSlcCode}/{arSltCode}/{arRefNo}/{clientIdAr}', 'LoansMasterInquiryController@index');
    Route::get('armaster-inquiry', 'LoansArMasterIquiryController@index');
    Route::get('armaster-inquiry/{id}', 'LoansArMasterIquiryController@index');
    Route::get('armaster-inquiry/{id}/ar-search-loan-inquiry', 'LoansArMasterIquiryController@index');
    Route::get('armaster-inquiry/{arBrCode}/{arSlcCode}/{arSltCode}/{arRefNo}/{clientIdAr}', 'LoansArMasterIquiryController@index');
    Route::get('batch-edit-loan-setup', 'LoanBatchEditSetupController@index');
    Route::get('loan-search', 'LoanSearchPageController@index');
    Route::get('loan-search/{id}/loan-search-loan', 'LoanSearchLoanPageController@index');
    Route::get('loan-ar-search', 'LoanArSearchPageController@index');
    Route::get('loan-master-inquiry-search', 'LoanSearchInquiryPageController@index');
    Route::get('loan-armaster-inquiry-search', 'LoanArSearchInquiryController@index');
    Route::get('generate', 'LoansGeneratePageController@index');
    Route::get('maintenance', 'LoansMaintenancePageController@index');
    Route::get('unearned-interest', 'LoansUnearnedInterestPageController@index');
    Route::get('unearned-collection-fee', 'LoansUnearnedCollectionFeePageController@index');
    Route::get('batch-process-maintenance', 'LoansBatchProcessMaintenancePageController@index');
    Route::get('amortization-sched-cal', 'LoansAmortizationSchedCalPageController@index');
    Route::get('aging-of-receivables', 'LoansAgingOfReceivablesPageController@index');
    Route::get('analysis-of-receivables', 'LoansAnalysisOfReceivablesPageController@index');
    Route::get('override', 'LoansOverridePagecontroller@index');
    Route::get('loans-account-number-inquiry', 'LoansAccNumInquiryPageController@index');
    Route::get('loans-app-search','LoanAppSearchPageController@index');
    Route::get('loans-app-search/{status}','LoanAppSearchPageController@index');
    
});

Route::prefix('deposits')->group(function (){
    Route::get('/', 'DepositsPageController@index');
    Route::get('savings-deposit', 'SavingsDepositPageController@index');
    Route::get('time-deposit', 'TimeDepositPageController@index');
    Route::get('share-capital', 'ShareCapitalPageController@index');
    Route::get('inquiry-savings', 'InquirySavingsPageController@index');
    Route::get('inquiry-time', 'InquiryTimePageController@index');
    Route::get('inquiry-share', 'InquirySharePageController@index');
    Route::get('inquiry-dividend', 'InquiryDividendPageController@index');
    Route::get('inquiry-patronage', 'InquiryPatronagePageController@index');
    Route::get('inquiry-interest', 'InquiryInterestPageController@index');
    Route::get('dormancy-tagging', 'DormancyPageController@index');
    Route::get('member-generate', 'DepositsMemberGeneratePageController@index');
    Route::get('member-maintenance', 'DepositsMemberMaintenancePageController@index');
    Route::get('avg-generate', 'ShareCapitalGeneratePageController@index');
    Route::get('share-capital-control', 'ShareCapitalControlPageController@index');
    Route::get('compute', 'DepositsComputePageController@index');
    Route::get('journalize', 'JournalizePageController@index');
    Route::get('maintenance-dividend', 'MaintenanceDividendPageController@index');
    Route::get('maintenance-patronage', 'MaintenancePatronagePageController@index');
    Route::get('maintenance-special', 'MaintenanceSpecialPageController@index');
    Route::get('int-generate', 'DepositsIntGeneratePageController@index');
    Route::get('int-maintenance', 'DepositsIntMaintenancePageController@index');
    Route::get('accr-generate', 'DepositsAccrGeneratePageController@index');
    Route::get('accr-maintenance', 'DepositsAccrMaintenancePageController@index');
    Route::get('time-generate', 'DepositsTimeGeneratePageController@index');
    Route::get('time-maintenance', 'DepositsTimeMaintenancePageController@index');
    Route::get('savings-listing', 'DepositsSavingsListingPageController@index');
    Route::get('time-listing', 'DepositsTimeListingPageController@index');
    Route::get('share-capital-listing', 'DepositsShareCapitalListingPageController@index');
    Route::get('time-certificate', 'DepositsTimeCertificatePageController@index');
    Route::get('compounding-interest', 'DepositsCompoundingInterestPageController@index');
    Route::get('override', 'DepositsOverridePageController@index');
    Route::get('savings-deposit-search', 'DepositsSavingsDepositSearchPageController@index');
    Route::get('sdsearch/{id}/savings-deposit-search', 'DepositsSavingsDepositSearchPageController@index');
    Route::get('sdsearch/{id}/inquiry-savings-search', 'DepositsSavingsDepositSearchPageController@index');
    Route::get('tdsearch/{id}/time-deposit-search', 'DepositsTimeDepositSearchPageController@index');
    Route::get('tdsearch/{id}/inquiry-time-search', 'DepositsInquiryTimeSearchPageController@index');
    Route::get('savings-deposit/{id}', 'SavingsDepositPageController@index');
    Route::get('savings-deposit/{sdBrCode}/{sdSlcCode}/{sdSltCode}/{sdRefNo}/{clientIdSd}','SavingsDepositPageController@index');
    Route::get('time-deposit-search', 'DepositsTimeDepositSearchPageController@index');
    Route::get('time-deposit/{id}','TimeDepositPageController@index');
    Route::get('time-deposit/{tdBrCode}/{tdSlcCode}/{tdSltCode}/{tdRefNo}/{clientIdTd}','TimeDepositPageController@index');
    Route::get('inquiry-savings-search', 'DepositsInquirySavingsSearchPageController@index');
    Route::get('inquiry-savings/{id}','InquirySavingsPageController@index');
    Route::get('inquiry-savings/{sdBrCode}/{sdSlcCode}/{sdSltCode}/{sdRefNo}/{clientIdSd}','InquirySavingsPageController@index');
    Route::get('inquiry-share-search', 'DepositsInquiryShareSearchPageController@index');
    Route::get('inquiry-share-search/{id}/inquiry-share-search-deposit','DepositsInquiryShareSearchPageController@index');
    Route::get('inquiry-share/{id}','InquirySharePageController@index');
    Route::get('inquiry-time/{id}', 'InquiryTimePageController@index');
    Route::get('inquiry-time/{tdBrCode}/{tdSlcCode}/{tdSltCode}/{tdRefNo}/{ClientIdTd}','InquiryTimePageController@index');
    Route::get('inquiry-time-search','DepositsInquiryTimeSearchPageController@index');
    Route::get('share-capital-search', 'DepositShareCapitalSearchController@index');
    Route::get('share-capital-search/{id}/share-capital-search-deposit', 'DepositShareCapitalSearchController@index');
    Route::get('share-capital/{id}', 'DepositShareCapitalSearchController@index');
    Route::get('share-capital/{scBrCode}/{scSlcCode}/{scSltCode}/{scRefNo}/{clientIdSc}', 'ShareCapitalPageController@index');
    Route::get('inquiry-share/{scBrCode}/{scSlcCode}/{scSltCode}/{scRefNo}/{clientIdSc}', 'InquirySharePageController@index');
    Route::get('inquiry-dividend-search', 'DepositsInquiryDividendSearchPageController@index');
    Route::get('inquiry-dividend-search/{id}/inquiry-dividend-search-deposit', 'DepositsInquiryDividendSearchController@index');
    Route::get('inquiry-dividend/{id}', 'InquiryDividendPageController@index');
    Route::get('inquiry-patronage-search', 'DepositsInquiryPatronageSearchPageController@index');
    Route::get('inquiry-patronage-search/{id}/inquiry-dividend-search-deposit', 'DepositPatronageSearchController@index');
    Route::get('inquiry-patronage/{id}', 'InquiryPatronagePageController@index');
    Route::get('inquiry-interest-search', 'DepositsInquiryInterestSearchPageController@index');
    Route::get('inquiry-interest-search/{id}/inquiry-interest-search-deposit', 'DepositInterestSearchController@index');
    Route::get('inquiry-interest/{id}', 'InquiryInterestPageController@index');
    Route::get('int-maintenance-search','DepositsIntMaintenanceSearchPageController@index');
    Route::get('accr-maintenance-search','DepositsAccrMaintenanceSearchPageController@index');
    Route::get('time-maintenance-search','DepositsTimeMaintenanceSearchPageController@index');
    Route::get('inquiry-dividend/{trCode}/{trYear}/{trCtlNo}/{trDocNo}','InquiryDividendPageController@index');
    Route::get('inquiry-interest/{trCode}/{trYear}/{trCtlNo}/{trDocNo}','InquiryInterestPageController@index');;
    Route::get('maintenance-dividend-search','DepositsMaintenanceDividendSearchPageController@index');
    Route::get('maintenance-patronage-search','DepositsMaintenancePatronageSearchPageController@index');
    Route::get('maintenance-special-search','DepositsMaintenanceSpecialSearchPageController@index');
    Route::get('inquiry-dividend/{trCode}/{trYear}/{trCtlNo}/{trDocNo}','InquiryDividendPageController@index');
    Route::get('int-maintenance/{trCode}/{trYear}/{trCtlNo}/{trDocNo}','DepositsIntMaintenancePageController@index');
    Route::get('time-maintenance/{trCode}/{trYear}/{trCtlNo}/{trDocNo}','DepositsTimeMaintnanceePageController@index');
    Route::get('accr-maintenance/{trCode}/{trYear}/{trCtlNo}/{trDocNo}','DepositsAccrMaintenancePageController@index');
    Route::get('inquiry-patronage/{trCode}/{trYear}/{trCtlNo}/{trDocNo}','InquiryPatronagePageController@index');
    Route::get('avg-control-print','DepositsAvgControlPrintPageController@index');
});

Route::prefix('inventory')->group(function (){
    Route::get('/', 'InventoryPageController@index');
    Route::get('items-master', 'InvItemsMasterPageController@index');
    Route::get('items-inquiry', 'InvItemsInquiryPageController@index');
    Route::get('items-listing', 'InvItemsInquiryPageController@index');
    Route::get('vendors-master', 'InvVendorsMasterPageController@index');
    Route::get('vendors-inquiry', 'InvVendorsInquiryPageController@index');
    Route::get('vendors-listing', 'InvVendorsListingPageController@index');
    Route::get('purchase-master', 'InvPurchaseMasterPageController@index');
    Route::get('purchase-inquiry', 'InvPurchaseInquiryPageController@index');
    Route::get('purchase-listing','InvPurchaseListingPageController@index');
    Route::get('physical-master','InvPhysicalMasterPageController@index');
    Route::get('physical-inquiry','InvPhysicalInquiryPageController@index');
    Route::get('physical-listing','InvPhysicalListingPageController@index');
    Route::get('stocks-master','InvStocksMasterPageController@index');
    Route::get('stocks-inquiry','InvStocksInquiryPageController@index');
    Route::get('stocks-listing','InvStocksListingPageController@index');
    Route::get('inventory-payment','InvInventoryPaymentPageController@index');
    Route::get('inventory-item','InvInventoryItemPageController@index');
    Route::get('receiving-voucher','InvReceivingVoucherPageController@index');
    Route::get('receiving-vinquiry','InvReceivingVinquiryPageController@index');
    Route::get('override', 'InvOverridePageController@index');
    Route::get('transaction', 'InvTransactionPageController@index');
    Route::get('brand-master','InvBrandMasterPageController@index');
    Route::get('common-master', 'InvCommonNameMasterPageController@index');
    Route::get('item-class-master', 'InvItemClassMasterPageController@index');
    Route::get('item-sub-master', 'InvItemSubMasterPageController@index');
    Route::get('item-unit-master', 'InvItemUnitMasterPageController@index');
    Route::get('item-location-master', 'InvItemLocationMasterPageController@index');
    Route::get('points-master', 'InvPointsMasterPageController@index');
    Route::get('inv-master-search', 'InvMasterSearchPageController@index');
    Route::get('items-master/{id}', 'InvItemsMasterPageController@index');
});

Route::prefix('other-mod')->group(function (){      
    Route::get('/', 'OtherModPageController@index');
    Route::get('maintenance-accounts-payable', 'OtherModMaintenanceAccountsPayablePageController@index');
    Route::get('maintenance-accounts-payable/{id}', 'OtherModMaintenanceAccountsPayablePageController@index');
    Route::get('maintenance-accounts-payable/{apBrCode}/{apSlcCode}/{apSltCode}/{apRefNo}/{clientIdAp}','OtherModMaintenanceAccountsPayablePageController@index');
    Route::get('maintenance-ap-search', 'OtherModMaintenanceAccountsPayableSearchController@index');
    Route::get('apsearch/{id}/maintenance-ap-search', 'OtherModMaintenanceAccountsPayableSearchController@index');
    Route::get('maintenance-subsidiary-ledger', 'OtherModMaintenanceSubsidiaryLedgerPageController@index');
    Route::get('maintenance-subsidiary-ledger/{id}', 'OtherModMaintenanceSubsidiaryLedgerPageController@index');
    Route::get('maintenance-subsidiary-ledger/{oslBrCode}/{oslSlcCode}/{oslSltCode}/{oslRefNo}/{clientIdOsl}','OtherModMaintenanceSubsidiaryLedgerPageController@index');
    Route::get('maintenance-sl-search', 'OtherModMaintenanceSubsidiaryLedgerSearchPageController@index');
    Route::get('oslsearch/{id}/maintenance-sl-search', 'OtherModMaintenanceSubsidiaryLedgerSearchPageController@index');
    Route::get('inquiry-accounts-payable', 'OtherModInquiryAccountsPayablePageController@index');
    Route::get('inquiry-accounts-payable/{id}', 'OtherModInquiryAccountsPayablePageController@index');
    Route::get('inquiry-accounts-payable/{apBrCode}/{apSlcCode}/{apSltCode}/{apRefNo}/{clientIdAp}','OtherModInquiryAccountsPayablePageController@index');
    Route::get('inquiry-ap-search', 'OtherModInquiryAccountsPayableSearchController@index');
    Route::get('apsearch/{id}/inquiry-ap-search', 'OtherModInquiryAccountsPayableSearchController@index');
    Route::get('inquiry-subsidiary-ledger', 'OtherModInquirySubsidiaryLedgerPageController@index');
    Route::get('inquiry-subsidiary-ledger/{id}', 'OtherModInquirySubsidiaryLedgerPageController@index');
    Route::get('inquiry-subsidiary-ledger/{oslBrCode}/{oslSlcCode}/{oslSltCode}/{oslRefNo}/{clientIdOsl}','OtherModInquirySubsidiaryLedgerPageController@index');
    Route::get('inquiry-sl-search', 'OtherModInquirySubsidiaryLedgerSearchPageController@index');
    Route::get('oslsearch/{id}/inquiry-sl-search', 'OtherModInquirySubsidiaryLedgerSearchPageController@index');
    Route::get('st-others-computation', 'OtherModSTOthersComputationPageController@index');
    Route::get('st-payroll-computation', 'OtherModSTPayrollComputationPageController@index');
    Route::get('st-setup-annual', 'OtherModSTSetupAnnualPageController@index');
    Route::get('report-ap-listing', 'OtherModReportAPListingPageController@index');
    Route::get('other-al-listing', 'OtherModReportOtherALListingPageController@index');
    Route::get('report-true-money-transaction-listing', 'OtherModReportTrueMoneyTransactionListingPageController@index');
    Route::get('tools', 'OtherModToolsPageController@index');
    Route::get('st-maintenance', 'OtherModSTMaintenancePageController@index');
});

Route::prefix('setup')->group( function () {
    Route::get('/', 'SetupPageController@index');
    Route::get('chart-of-accounts', 'SetupChartOfAccountsPageController@index');
    Route::get('conso-chart-of-accounts', 'SetupConsoChartOfAccountsPageController@index');
    Route::get('departments','SetupDepartmentsPageController@index');
    Route::get('bank-code-table','SetupBankCodeTablePageController@index');
    Route::get('collectors','SetupCollectorsPageController@index');
    Route::get('deduction-group','SetupDeductionGroupPageController@index');
    Route::get('code-storage','SetupCodeStoragePageController@index');
    Route::get('holidays','SetupHolidaysPageController@index');
    Route::get('initialize-connections','SetupInitializeConnectionsPageController@index');
    Route::get('override','SetupOverridePageController@index');
    Route::get('subsidiary-ledger-sl-types', 'SetupSubsidiaryLedgerSLTypesPageController@index');
    Route::get('account-group-sectoral', 'SetupAccountGroupSectoralPageController@index');
    Route::get('account-group-occupational', 'SetupAccountGroupOccupationalPageController@index');
    Route::get('account-group-geo', 'SetupAccountGroupGeoPageController@index');
    Route::get('account-group-geo/{geoId}/{geoBrCode}', 'SetupAccountGroupGeoPageController@index');
    Route::get('account-group-empcode', 'SetupAccountGroupEmpCodePageController@index');
    Route::get('account-group-educ-school', 'SetupAccountGroupEducSchoolPageController@index');
    Route::get('account-group-educ-section', 'SetupAccountGroupEducSectionPageController@index');
    Route::get('account-group-restriction', 'SetupAccountGroupRestrictionPageController@index');
    Route::get('loan-loan-purpose-table', 'SetupLoanLoanPurposeTablePageController@index');
    Route::get('industry-section', 'SetupIndIndustryCodePageController@index');
    Route::get('industry-division', 'SetupIndSectionPageController@index');
    Route::get('industry-industry-code', 'SetupIndDivisionPageController@index');
    Route::get('time-deposit-rate', 'SetupTimeDepositRatePageController@index');
    Route::get('email-settings', 'SetupEmailSettingsPageController@index');
    Route::get('priority-object', 'SetupPriorityObjectPageController@index');
    Route::get('queuing-settings', 'SetupQueuingSettingsPageController@index');
    Route::get('cluster-setup-cluster', 'SetupClusterSetupClusterPageController@index');
    Route::get('sharecapital-pricestock', 'SetupShareCapitalPriceStockPageController@index');
    Route::get('account-group-geo-search', 'SetupGeoGraphicalSearchController@index');
});

Route::prefix('system')->group( function () {
Route::get('/', 'SystemPageController@index');
Route::get('environment-branch-information', 'SystemMaintenanceEnvironmentBranchInformationPageController@index');
Route::get('environment-workstation-parameters', 'SystemMaintenanceEnvironmentWorkstationParametersPageController@index');
Route::get('set-system-date', 'SystemSetSystemDatePageController@index');
Route::get('database-management', 'SystemDatabaseManagementPageController@index');
Route::get('connection-monitor', 'SystemConnectionMonitorPageController@index');
Route::get('interest-on-deposits', 'SystemInterestOnDepositsPageController@index');
Route::get('dividend', 'SystemDividendPageController@index');
Route::get('patronage', 'SystemPatronagePageController@index');
Route::get('live-update', 'SystemLiveUpdatePageController@index');
Route::get('user-access', 'SystemUserAccessPageController@index');
Route::get('user-access-rights-inquiry', 'SystemUserAccessRightsInquiryPageController@index');
Route::get('activity-logs', 'SystemActivityLogsPageController@index');
Route::get('loan-logs', 'SystemLoanLogsPageController@index');
Route::get('loan-application', 'SystemLoanApplicationPageController@index');
Route::get('user-access-rights-listing', 'SystemUserAccessRightsListingPageController@index');
Route::get('user-activity-logs-listing', 'SystemUserActivityLogsListingPageController@index');
Route::get('transfer-to-listing', 'SystemTransferToListingPageController@index');
Route::get('transfer-from-listing', 'SystemTransferFromListingPageController@index');
Route::get('migrate-coop', 'SystemMigrateCoopPageController@index');
Route::get('migrate-holy-cross', 'SystemMigrateHolyCrossPageController@index');
Route::get('tag-clients', 'SystemTagClientsPageController@index');
Route::get('transfers-to-branch', 'SystemTransfersToBranchPageController@index');
Route::get('transfers-from-branch', 'SystemTransfersFromBranchPageController@index');
Route::get('maintenance', 'SystemMaintenancePageController@index');
Route::get('download-table', 'SystemDownloadTablePageController@index');
Route::get('upload-table', 'SystemUploadTablePageController@index');
Route::get('override', 'SystemOverridePageController@index');
});


Route::prefix('reports')->group( function () {
    Route::get('/', 'ReportsPageController@index');
    Route::get('client-listing', 'ReportsClientListingPageController@index');
    Route::get('client-overall','ReportsClientOverallPageController@index');
    Route::get('client-summary', 'ReportsClientSummaryPageController@index');
    Route::get('transaction-transaction-listing', 'ReportsTransactionTransactionListingPageController@index');
    Route::get('transaction-coci-listing', 'ReportsTransactionCociListingPageController@index');
    Route::get('receivable-analysis', 'ReportsReceivableAnalysisPageController@index');
    Route::get('receivable-aging', 'ReportsReceivableAgingPageController@index');
    Route::get('receivable-collection', 'ReportsReceivableCollectionPageController@index');
    Route::get('savings-deposits-listing', 'ReportsSavingsDepositsListingPageController@index');
    Route::get('share-capital-listing', 'ReportsShareCapitalListingPageController@index');
    Route::get('capital-stock-certificate', 'ReportsCapitalStockCertificatePageController@index');
    Route::get('time-deposits-listing', 'ReportsTimeDepositsListingPageController@index');
    Route::get('time-printing', 'ReportsTimePrintingPageController@index');
    Route::get('accounts-payable-listing', 'ReportsAccountsPayableListingPageController@index');
    Route::get('other-sl-listing', 'ReportsOtherSLListingPageController@index');
    Route::get('insurance-remittance-report', 'ReportsInsuranceRemittanceReportPageController@index');
    Route::get('preferred-investment-certificate', 'ReportsPreferredInvestmentCertificatePageController@index');
    Route::get('damayan-enrollment-certificate', 'ReportsDamayanEnrollmentCertificatePageController@index');
    Route::get('cisa', 'ReportsCisaPageController@index');
    Route::get('front-office-reports', 'ReportsFrontOfficeReportsPageController@index');
    Route::get('financial-balance', 'ReportsFinancialBalancePageController@index');
    Route::get('financial-income', 'ReportsFinancialIncomePageController@index');
    Route::get('financial-trial', 'ReportsFinancialTrialPageController@index');
    Route::get('financial-general', 'ReportsFinancialGeneralPageController@index');
    Route::get('financial-gl-transaction', 'ReportsFinancialGlTransactionPageController@index');
    Route::get('bir-compliance', 'ReportsBirCompliancePageController@index');
    Route::get('miscellaneous-sl-detail', 'ReportsMiscellaneousSlDetailPageController@index');
    Route::get('tool-override', 'ReportsToolOverridePageController@index');
});

Route::prefix('play-to-save')->group(function(){
    Route::get('/', 'PlayToSavePageController@index');
    Route::get('p2s-sixdigit-num', 'PlayToSaveSixDigitNumPageController@index');
    Route::get('p2s-threedigit-num', 'PlayToSaveThreeDigitNumPageController@index');
    Route::get('p2s-six-digit-registration', 'PlayToSaveRegistrationPageController@index');
    Route::get('p2s-sixdigit-winner', 'PlayToSaveSixDigitWinnerPageController@index');
    Route::get('p2s-threedigit-winner', 'PlayToSaveThreeDigitWinnerPageController@index');
    Route::get('p2s-sixdigit-search', 'PlayToSaveSearchSixDigitPageController@index');
    Route::get('p2s-threedigit-search', 'PlayToSaveSearchThreeDigitPageController@index');
    Route::get('p2s-sixdigit-winner/{id}/{sixdigit}', 'PlayToSaveSixDigitWinnerPageController@index');
    Route::get('p2s-threedigit-winner/{id}/{threedigit}', 'PlayToSaveThreeDigitWinnerPageController@index');
    Route::get('p2s-stabs', 'PlayToSaveStabsPageController@index');
    Route::get('p2s-number-selection', 'PlayToSaveNumberSelectionPageController@index');
    Route::get('p2s-stabs-search', 'PlayToSaveSerialStabsSearchPageController@index');
    Route::get('p2s-three-digit-registration', 'PlayToSaveThreeDigitRegistrationPageController@index');
    Route::get('p2s-three-digit-number-selection', 'PlayToSaveThreeDigitNumberSelectionPageController@index');
    Route::get('p2s-stabs-list', 'PlayToSaveTicketsListPageController@index');
    Route::get('p2s-stabs-list-six', 'PlayToSaveTicketsList6PageController@index');
    Route::get('p2s-three-digit-number-selection/{id}/{branch}/{serial}/{trId}/{clientid}', 'PlayToSaveThreeDigitNumberSelectionPageController@index');
    Route::get('p2s-number-selection/{id}/{branch}/{serial}', 'PlayToSaveNumberSelectionPageController@index');
    Route::get('combo3', 'PlayToSaveThreeDigitNumberSelectionPageController@downloadExcel');
    Route::get('combo6', 'PlayToSaveNumberSelectionPageController@downloadExcel6');
    Route::get('p2s-stabs-list/{id}/{clientid}', 'PlayToSaveTicketsListPageController@index');
    Route::get('p2s-stabs-list-six/{id}/{clientid}', 'PlayToSaveTicketsList6PageController@index');
    Route::get('p2s-three-digit-number-selection/{id}/{branch}/{serial}/{trId}/{clientid}', 'PlayToSaveThreeDigitNumberSelectionPageController@index');
    Route::get('p2s-number-selection/{id}/{branch}/{serial}/{trId}/{clientid}', 'PlayToSaveNumberSelectionPageController@index');
    Route::get('p2s-stabs-all', 'PlayToSaveTicketsPageController@index');
});
