<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateWkfanalysisTable extends Migration {

	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('wkfanalysis', function(Blueprint $table)
		{
			$table->string('BR_CODE', 4)->nullable();
			$table->string('CLIENTID', 12)->nullable();
			$table->string('CLIENTNAME', 100)->nullable();
			$table->string('HOMEADDRESS', 200)->nullable();
			$table->string('BUSINESSADDRESS', 200)->nullable();
			$table->string('HOMETELNO', 100)->nullable();
			$table->string('BUSINESSTELNO', 100)->nullable();
			$table->string('GEOGRP', 100)->nullable();
			$table->string('GENDER', 20)->nullable();
			$table->boolean('CIVILSTATUS')->nullable();
			$table->string('CLIENTTYPE', 20)->nullable();
			$table->string('ACCOUNTTYPE', 20)->nullable();
			$table->string('AGE', 10)->nullable();
			$table->string('SLDESCR', 50)->nullable();
			$table->string('REF_NO', 20)->nullable();
			$table->date('TR_DATE')->nullable();
			$table->string('TERM', 50)->nullable();
			$table->string('PAYMENTMODE', 100)->nullable();
			$table->date('MATURITYDATE')->nullable();
			$table->string('STATUS', 45)->nullable();
			$table->decimal('PRINCIPALAMT', 15)->nullable();
			$table->decimal('PRINCIPALBAL', 15)->nullable();
			$table->decimal('SHOULDBEPAY', 15)->nullable();
			$table->decimal('ACTUALPAY', 15)->nullable();
			$table->decimal('DELAYEDPAY', 15)->nullable();
			$table->decimal('ADVANCEPAY', 15)->nullable();
			$table->decimal('PRINDUE', 15)->nullable();
			$table->decimal('INTDUE', 15)->nullable();
			$table->decimal('PENDUE', 15)->nullable();
			$table->decimal('PRINOVR', 15)->nullable();
			$table->decimal('INTOVR', 15)->nullable();
			$table->decimal('PENOVR', 15)->nullable();
			$table->decimal('SAVINGS', 15)->nullable();
			$table->decimal('SHARECAPITAL', 15)->nullable();
			$table->date('LASTTRANSDATE_PRIN')->nullable();
			$table->date('LASTTRANSDATE_INT')->nullable();
			$table->date('LASTTRANSDATE_PEN')->nullable();
			$table->decimal('NDAYS_PASTDUE', 15, 0)->nullable();
			$table->string('ACCOUNTSTATUS', 50)->nullable();
			$table->string('ACCOUNTOFFICER', 45)->nullable();
			$table->string('COLL_TYPE', 45)->nullable();
			$table->string('COLL_VAL', 45)->nullable();
			$table->text('COLL_DESCR', 65535)->nullable();
			$table->string('COMAKER')->nullable();
			$table->text('REMARKS', 65535)->nullable();
			$table->decimal('AMORTIZATION', 15)->nullable();
			$table->decimal('DEL_AMORT', 15)->nullable();
			$table->decimal('ARRIERS', 15)->nullable();
			$table->decimal('MONTHS_DELAYED', 15)->nullable();
			$table->string('ACCOUNTSTATUSCODE', 45)->nullable();
			$table->decimal('NDAYS_DELAYED', 15)->nullable();
			$table->string('SLC_CODE', 100)->nullable();
			$table->string('CREDITINV', 45)->nullable();
			$table->string('ISINSKEDEXCL', 45)->nullable();
			$table->decimal('INTRATE', 15)->nullable();
			$table->string('AMORTYPE', 100)->nullable();
			$table->string('DIMB_FREQ', 100)->nullable();
			$table->string('IPMT_MODE', 100)->nullable();
			$table->decimal('PENRATE', 15)->nullable();
			$table->string('PEN_MODE', 100)->nullable();
			$table->string('DD_FLAG', 100)->nullable();
			$table->string('ND_FLAG', 100)->nullable();
			$table->string('REFNUM', 10)->nullable();
			$table->decimal('CRLIMIT', 15)->nullable();
			$table->decimal('ACCRUEDINTRECVBLE', 15)->nullable();
			$table->boolean('SLT_CODE');
			$table->string('DOSRITAGx', 200)->nullable();
			$table->string('LOANCLASSx', 200)->nullable();
			$table->decimal('SHOULDBEINT', 15)->nullable();
			$table->decimal('SHOULDBEPEN', 15)->nullable();
			$table->decimal('ACTUALINTPAID', 15)->nullable();
			$table->decimal('ACTUALPENPAID', 15)->nullable();
			$table->string('EMPLOYERCODE', 50)->nullable();
			$table->string('LOANPURPOSE', 50)->nullable();
			$table->string('SECTORAL', 100)->nullable();
			$table->string('OCCUPATIONAL', 100)->nullable();
			$table->decimal('ARBALANCE', 15)->nullable();
			$table->decimal('COLLFEE', 15)->nullable();
			$table->string('PMESBATCHNUM', 50)->nullable();
			$table->date('PMESDATE')->nullable();
			$table->string('IDRECORDTYPE', 3);
			$table->string('PROVIDERCODE', 10);
			$table->date('SUBJREFDATE');
			$table->string('TITLE', 8)->nullable();
			$table->string('FIRSTNAME', 45)->nullable();
			$table->string('LASTNAME', 45)->nullable();
			$table->string('MIDDLENAME', 45)->nullable();
			$table->string('SURNAME', 45)->nullable();
			$table->string('NICKNAME', 45)->nullable();
			$table->string('OLDNAME', 45)->nullable();
			$table->date('DOB')->nullable();
			$table->string('POB', 60)->nullable();
			$table->string('COB', 3)->nullable();
			$table->string('NATIONALITY', 3)->nullable();
			$table->boolean('RESIDENT')->nullable();
			$table->boolean('DEPENDANTS')->nullable();
			$table->boolean('CARSOWNED')->nullable();
			$table->string('SPFNAME', 45)->nullable();
			$table->string('SPLNAME', 45)->nullable();
			$table->string('SPMNAME', 45)->nullable();
			$table->string('MOTHERFNAME', 45)->nullable();
			$table->string('MOTHERLNAME', 45)->nullable();
			$table->string('MOTHERMNAME', 45)->nullable();
			$table->string('FATHERFNAME', 45)->nullable();
			$table->string('FATHERLNAME', 45)->nullable();
			$table->string('FATHERMNAME', 45)->nullable();
			$table->string('FATHERSNAME', 45)->nullable();
			$table->string('ADD1TYPE', 3)->nullable();
			$table->string('ADD1STRNUM', 3)->nullable();
			$table->string('ADD1POSTALCODE', 3)->nullable();
			$table->string('ADD1SUBD', 3)->nullable();
			$table->string('ADD1BRGY', 3)->nullable();
			$table->string('ADD1CITY', 3)->nullable();
			$table->string('ADD1PROV', 3)->nullable();
			$table->string('ADD1COUNTRY', 3)->nullable();
			$table->string('ADD1OWNERTYPE', 3)->nullable();
			$table->date('ADD1OCCUSINCE')->nullable();
			$table->string('ADD2TYPE', 3)->nullable();
			$table->string('ADD2FULL', 400)->nullable();
			$table->string('ADD2STRNUM', 3)->nullable();
			$table->string('ADD2POSTALCODE', 3)->nullable();
			$table->string('ADD2SUBD', 3)->nullable();
			$table->string('ADD2BRGY', 3)->nullable();
			$table->string('ADD2CITY', 3)->nullable();
			$table->string('ADD2PROV', 3)->nullable();
			$table->string('ADD2COUNTRY', 3)->nullable();
			$table->string('ADD2OWNERTYPE', 3)->nullable();
			$table->date('ADD2OCCUSINCE')->nullable();
			$table->boolean('ID1PRIMTYPE')->nullable();
			$table->string('ID1PRIMNUM', 20)->nullable();
			$table->boolean('ID2PRIMTYPE')->nullable();
			$table->string('ID2PRIMNUM', 20)->nullable();
			$table->boolean('ID3PRIMTYPE')->nullable();
			$table->string('ID3PRIMNUM', 20)->nullable();
			$table->boolean('ID1SECTYPE')->nullable();
			$table->string('ID1SECNUM', 20)->nullable();
			$table->date('ID1SECISSUEDATE')->nullable();
			$table->string('ID1SECCOUNTRY', 3)->nullable();
			$table->date('ID1SECEXPDATE')->nullable();
			$table->string('ID1SECISSUEDBY', 45)->nullable();
			$table->boolean('ID2SECTYPE')->nullable();
			$table->string('ID2SECNUM', 20)->nullable();
			$table->date('ID2SECISSUEDATE')->nullable();
			$table->string('ID2SECCOUNTRY', 3)->nullable();
			$table->date('ID2SECEXPDATE')->nullable();
			$table->string('ID2SECISSUEDBY', 45)->nullable();
			$table->boolean('ID3SECTYPE')->nullable();
			$table->string('ID3SECNUM', 20)->nullable();
			$table->date('ID3SECISSUEDATE')->nullable();
			$table->string('ID3SECCOUNTRY', 3)->nullable();
			$table->date('ID3SECEXPDATE')->nullable();
			$table->string('ID3SECISSUEDBY', 45)->nullable();
			$table->boolean('CONTACT1TYPE')->nullable();
			$table->string('CONTACT1VAL', 100)->nullable();
			$table->boolean('CONTACT2TYPE')->nullable();
			$table->string('CONTACT2VAL', 100)->nullable();
			$table->string('EMPNAME', 120)->nullable();
			$table->string('EMPTIN', 16)->nullable();
			$table->string('EMPPHONE', 20)->nullable();
			$table->string('EMPPSIC', 8)->nullable();
			$table->string('EMPGROSS', 16)->nullable();
			$table->string('EMPMONTHLY', 3)->nullable();
			$table->string('EMPCURR', 5)->nullable();
			$table->string('EMPOCCUSTAT', 3)->nullable();
			$table->date('EMPHIREDFROM')->nullable();
			$table->date('EMPHIREDTO')->nullable();
			$table->string('EMPOCCUCODE', 8)->nullable();
			$table->string('SOLTRNAME', 45)->nullable();
			$table->string('SOLETR1ADDTYPE', 3)->nullable();
			$table->string('SOLETR1ADDFULL', 100)->nullable();
			$table->string('SOLETR1STRNUM', 100)->nullable();
			$table->string('SOLETR1POSTALCODE', 4)->nullable();
			$table->string('SOLETR1SUBD', 100)->nullable();
			$table->string('SOLETR1BRGY', 60)->nullable();
			$table->string('SOLETR1CITY', 50)->nullable();
			$table->string('SOLETR1PROV', 50)->nullable();
			$table->string('SOLETR1COUNTRY', 3)->nullable();
			$table->boolean('SOLETR1OWNER')->nullable();
			$table->date('SOLETR1SINCE')->nullable();
			$table->string('SOLETR2ADDTYPE', 3)->nullable();
			$table->string('SOLETR2ADDFULL', 100)->nullable();
			$table->string('SOLETR2STRNUM', 3)->nullable();
			$table->string('SOLETR2POSTALCODE', 3)->nullable();
			$table->string('SOLETR2SUBD', 3)->nullable();
			$table->string('SOLETR2BRGY', 3)->nullable();
			$table->string('SOLETR2CITY', 3)->nullable();
			$table->string('SOLETR2PROV', 3)->nullable();
			$table->string('SOLETR2COUNTRY', 2)->nullable();
			$table->boolean('SOLETR2OWNER')->nullable();
			$table->date('SOLETR2SINCE')->nullable();
			$table->boolean('SOLETR1IDTYPE')->nullable();
			$table->string('SOLETR1IDNUM', 16)->nullable();
			$table->boolean('SOLETR2IDTYPE')->nullable();
			$table->string('SOLETR2IDNUM', 16)->nullable();
			$table->boolean('SOLETR1CONTYPE')->nullable();
			$table->string('SOLETR1CONVAL', 100)->nullable();
			$table->boolean('SOLETR2CONTYPE')->nullable();
			$table->string('SOLETR2CONVAL', 100)->nullable();
			$table->string('CIRECORDTYPE', 3);
			$table->string('ROLE', 3);
			$table->string('CONTRACTNUM', 38);
			$table->boolean('CONTRACTTYPE');
			$table->string('CONTRACTPHASE', 3);
			$table->string('CONTRACTSTAT', 3)->nullable();
			$table->string('CURRENCY', 5);
			$table->string('ORIGCURRENCY', 5);
			$table->date('CONTRACT_REQDATE')->nullable();
			$table->date('CONTRACT_ENDPLANDATE')->nullable();
			$table->date('CONTRACT_ENDACTUALDATE')->nullable();
			$table->boolean('REORGCREDIT')->nullable();
			$table->string('BOARD_RESU', 3)->nullable();
			$table->smallInteger('INSTALLNUMBER')->unsigned();
			$table->string('TRANSACTION_TYPE', 3);
			$table->string('PURPOSE_CREDIT', 3)->nullable();
			$table->string('PAYMENTPERIODCITY', 2);
			$table->string('PAYMENTMETHOD', 3)->nullable();
			$table->decimal('MONTHYPAYMENTAMT', 15)->nullable();
			$table->date('FIRSTPAYMENTDATE');
			$table->decimal('LASTPAYMNTAMT', 15)->nullable();
			$table->date('NEXTPAYMNTDATE');
			$table->decimal('NEXTPAYMENT', 15)->nullable();
			$table->smallInteger('OUTSTANDINGPAYMNTNUM')->nullable();
			$table->decimal('OUTSTANDINGBAL', 15)->nullable();
			$table->boolean('OVERDUEPAYMNTNUM')->nullable();
			$table->decimal('OVERDUEPAYMNTAMT', 15)->nullable();
			$table->string('OVERDUEDAYS', 3)->nullable();
			$table->string('GOODTYPE', 1)->nullable();
			$table->string('GOODVALUE', 1)->nullable();
			$table->string('NEWUSEDCODE', 1)->nullable();
			$table->string('GOODBRAND', 1)->nullable();
			$table->string('MANUFACTRNG_DATE', 1)->nullable();
			$table->string('REGNUM', 1)->nullable();
			$table->string('GUARAN1NUM', 1)->nullable();
			$table->string('GUARAN1_SUBJNO', 38)->nullable();
			$table->string('GUARAN1NAME', 200)->nullable();
			$table->decimal('GUARAN1AMT', 15)->nullable();
			$table->string('GUARAN1CURR', 3)->nullable();
			$table->string('GUARAN1STARTDATE', 3)->nullable();
			$table->string('GUARAN1ENDDATE', 3)->nullable();
			$table->string('GUARAN1TYPE', 3)->nullable();
			$table->string('GUARAN1ASSETCODE', 3)->nullable();
			$table->string('GUARAN1ASSETDESC', 160)->nullable();
			$table->string('GUARAN1ASSETLOC', 3)->nullable();
			$table->decimal('GUARAN1ASSETAPPRAISEDVAL', 15)->nullable();
			$table->string('GUARAN1REGLINK', 3)->nullable();
			$table->string('GUARAN1CUSTTYPE', 3)->nullable();
			$table->string('GUARAN2NUM', 1)->nullable();
			$table->string('GUARAN2_SUBJNO', 38)->nullable();
			$table->string('GUARAN2NAME', 200)->nullable();
			$table->decimal('GUARAN2AMT', 15)->nullable();
			$table->string('GUARAN2CURR', 3)->nullable();
			$table->string('GUARAN2STARTDATE', 3)->nullable();
			$table->string('GUARAN2ENDDATE', 3)->nullable();
			$table->string('GUARAN2TYPE', 3)->nullable();
			$table->string('GUARAN2ASSETCODE', 3)->nullable();
			$table->string('GUARAN2ASSETDESC', 160)->nullable();
			$table->string('GUARAN2ASSETLOC', 3)->nullable();
			$table->decimal('GUARAN2ASSETAPPRAISEDVAL', 15)->nullable();
			$table->string('GUARAN2REGLINK', 3)->nullable();
			$table->string('GUARAN2CUSTTYPE', 3)->nullable();
			$table->string('GUARAN3NUM', 1)->nullable();
			$table->string('GUARAN3_SUBJNO', 38)->nullable();
			$table->string('GUARAN3NAME', 200)->nullable();
			$table->decimal('GUARAN3AMT', 15)->nullable();
			$table->string('GUARAN3CURR', 3)->nullable();
			$table->string('GUARAN3STARTDATE', 3)->nullable();
			$table->string('GUARAN3ENDDATE', 3)->nullable();
			$table->string('GUARAN3TYPE', 3)->nullable();
			$table->string('GUARAN3ASSETCODE', 3)->nullable();
			$table->string('GUARAN3ASSETDESC', 160)->nullable();
			$table->string('GUARAN3ASSETLOC', 3)->nullable();
			$table->decimal('GUARAN3ASSETAPPRAISEDVAL', 15)->nullable();
			$table->string('GUARAN3REGLINK', 3)->nullable();
			$table->string('GUARAN3CUSTTYPE', 3)->nullable();
			$table->string('GUARAN4NUM', 1)->nullable();
			$table->string('GUARAN4_SUBJNO', 38)->nullable();
			$table->string('GUARAN4NAME', 200)->nullable();
			$table->decimal('GUARAN4AMT', 15)->nullable();
			$table->string('GUARAN4CURR', 3)->nullable();
			$table->string('GUARAN4STARTDATE', 3)->nullable();
			$table->string('GUARAN4ENDDATE', 3)->nullable();
			$table->string('GUARAN4TYPE', 3)->nullable();
			$table->string('GUARAN4ASSETCODE', 3)->nullable();
			$table->string('GUARAN4ASSETDESC', 160)->nullable();
			$table->string('GUARAN4ASSETLOC', 3)->nullable();
			$table->decimal('GUARAN4ASSETAPPRAISEDVAL', 15)->nullable();
			$table->string('GUARAN4REGLINK', 3)->nullable();
			$table->string('GUARAN4CUSTTYPE', 3)->nullable();
			$table->string('GUARAN5NUM', 1)->nullable();
			$table->string('GUARAN5_SUBJNO', 38)->nullable();
			$table->string('GUARAN5NAME', 200)->nullable();
			$table->decimal('GUARAN5AMT', 15)->nullable();
			$table->string('GUARAN5CURR', 3)->nullable();
			$table->string('GUARAN5STARTDATE', 3)->nullable();
			$table->string('GUARAN5ENDDATE', 3)->nullable();
			$table->string('GUARAN5TYPE', 3)->nullable();
			$table->string('GUARAN5ASSETCODE', 3)->nullable();
			$table->string('GUARAN5ASSETDESC', 160)->nullable();
			$table->string('GUARAN5ASSETLOC', 3)->nullable();
			$table->decimal('GUARAN5ASSETAPPRAISEDVAL', 15)->nullable();
			$table->string('GUARAN5REGLINK', 3)->nullable();
			$table->string('GUARAN5CUSTTYPE', 3)->nullable();
			$table->string('GUARAN6NUM', 1)->nullable();
			$table->string('GUARAN6_SUBJNO', 38)->nullable();
			$table->string('GUARAN6NAME', 200)->nullable();
			$table->decimal('GUARAN6AMT', 15)->nullable();
			$table->string('GUARAN6CURR', 3)->nullable();
			$table->string('GUARAN6STARTDATE', 3)->nullable();
			$table->string('GUARAN6ENDDATE', 3)->nullable();
			$table->string('GUARAN6TYPE', 3)->nullable();
			$table->string('GUARAN6ASSETCODE', 3)->nullable();
			$table->string('GUARAN6ASSETDESC', 160)->nullable();
			$table->string('GUARAN6ASSETLOC', 3)->nullable();
			$table->decimal('GUARAN6ASSETAPPRAISEDVAL', 15)->nullable();
			$table->string('GUARAN6REGLINK', 3)->nullable();
			$table->string('GUARAN6CUSTTYPE', 3)->nullable();
			$table->string('LINKEDSUBJNO1', 38)->nullable();
			$table->string('LINKEDROLE1', 1)->nullable();
			$table->string('LINKEDNAME1', 220)->nullable();
			$table->string('LINKEDSUBJNO2', 38)->nullable();
			$table->string('LINKEDROLE2', 1)->nullable();
			$table->string('LINKEDNAME2', 220)->nullable();
			$table->string('LINKEDSUBJNO3', 38)->nullable();
			$table->string('LINKEDROLE3', 1)->nullable();
			$table->string('LINKEDNAME3', 220)->nullable();
			$table->string('LINKEDSUBJNO4', 38)->nullable();
			$table->string('LINKEDROLE4', 1)->nullable();
			$table->string('LINKEDNAME4', 220)->nullable();
			$table->string('LINKEDSUBJNO5', 38)->nullable();
			$table->string('LINKEDROLE5', 1)->nullable();
			$table->string('LINKEDNAME5', 220)->nullable();
			$table->string('LINKEDSUBJNO6', 38)->nullable();
			$table->string('LINKEDROLE6', 1)->nullable();
			$table->string('LINKEDNAME6', 220)->nullable();
		});
	}


	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::drop('wkfanalysis');
	}

}
